#compile for progressBar
progress: main.cpp 
	g++ -std=c++11 main.cpp -o progress 
	@echo "compile over run after "
run: progress
	 ./progress
git:
	git add .
	@git commit -m "make auto commit"
clean:
	rm progress